// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/angular-dynamic-locale/angular-dynamic-locale.d.ts
declare module "angular-dynamic-locale" {
	import ng = angular.dynamicLocale;
	export = ng;
}

declare namespace angular.dynamicLocale {

	interface tmhDynamicLocaleService {
		set(locale: string): void;
		get(): string;
	}

	interface tmhDynamicLocaleProvider extends angular.IServiceProvider {
		localeLocationPattern(location: string): tmhDynamicLocaleProvider;
		localeLocationPattern(): string;
		useStorage(storageName: string): void;
		useCookieStorage(): void;
	}
}